lang_list = [
    "English",
    "Русский",
    "Türkçe",
    "Español",
    "فارسی",
    "Français",
    "Deutsch",
    "日本語",
    "Tiếng Việt Nam",
    "中文",
    "العربية",
    "Português",
    "Ελληνικά",
    "Italiano",
    "Bahasa Indonesia",
    "Українська",
    "Polski",
    "Nederlands",
    "한국어",
    "עברית",
    "ภาษาไทย",
    "Český Jazyk",
    "Română",
    "Svenska",
    "Српски",
    "Magyar",
    "Dansk",
    "български език",
    "Suomi",
    "Slovenčina",
    "Hrvatski",
    "हिन्दी",
    "Lietuvių",
    "Norsk",
    "بهاس ملايو"
]
